from __future__ import annotations

LANGUAGES = {
    "O‘zbekcha": "uz",
    "Русский": "ru",
    "English": "en",
}

TEXT = {
    "uz": {
        "app_title": "O‘zbekiston AI Matematika Mentori",
        "tagline": "Har bir yechim qadamini tekshiradigan, xatolarni tahlil qiladigan va mos mashqlar tavsiya etadigan sun’iy intellekt yordamchisi.",
        "country": "Mamlakat",
        "country_value": "O‘zbekiston",
        "language": "Interfeys tili",
        "profile": "O‘quvchi profili",
        "name": "Ism yoki taxallus",
        "region": "Hudud",
        "stage": "Ta’lim bosqichi",
        "grade": "Sinf/kurs",
        "level": "Hozirgi daraja",
        "save_profile": "Profilni saqlash",
        "profile_saved": "Profil saqlandi.",
        "home": "Bosh sahifa",
        "practice": "Mashq",
        "dashboard": "Tahlil",
        "bank": "Masalalar banki",
        "responsible": "Mas’uliyatli AI",
        "choose_topic": "Mavzuni tanlang",
        "choose_problem": "Masalani tanlang",
        "difficulty": "Qiyinlik",
        "problem": "Masala",
        "instructions": "Har bir matematik qadamni yangi qatordan yozing. `*`, `/`, `^`, `sqrt(...)`, `sin(...)` va tenglik uchun `=` ishlatishingiz mumkin.",
        "solution_steps": "Yechim qadamlari",
        "evaluate": "Qadamlarni tekshirish",
        "need_steps": "Kamida bitta yechim qadamini kiriting.",
        "result": "Qadamlar tahlili",
        "step": "Qadam",
        "status": "Holat",
        "diagnosis": "Xato turi",
        "feedback": "AI izohi",
        "correct": "To‘g‘ri",
        "incorrect": "Tekshirish kerak",
        "score": "Natija",
        "recommended": "Keyingi tavsiya",
        "liked": "Foydali",
        "disliked": "Foydali emas",
        "no_attempts": "Hali urinishlar yo‘q. Mashq sahifasida masala yeching.",
        "attempts": "Urinishlar",
        "accuracy": "Qadamlar aniqligi",
        "weaknesses": "Ko‘p uchragan xatolar",
        "download": "Natijalarni CSV shaklida yuklab olish",
        "all_topics": "Barcha mavzular",
        "about_scope": "Ushbu versiya faqat O‘zbekiston o‘quvchilari uchun sozlangan: mamlakat o‘zgarmaydi, 1–11-sinflar, akademik litsey va universitet bosqichlari, O‘zbekiston hududlari hamda UZS kontekstli masalalar mavjud.",
        "not_endorsement": "Bu namuna O‘zbekiston davlat organlarining rasmiy mahsuloti yoki tasdiqlangan baholash tizimi emas.",
    },
    "ru": {
        "app_title": "AI-наставник по математике для Узбекистана",
        "tagline": "Помощник, который проверяет каждый шаг решения, анализирует ошибки и рекомендует подходящие задания.",
        "country": "Страна",
        "country_value": "Узбекистан",
        "language": "Язык интерфейса",
        "profile": "Профиль ученика",
        "name": "Имя или псевдоним",
        "region": "Регион",
        "stage": "Уровень образования",
        "grade": "Класс/курс",
        "level": "Текущий уровень",
        "save_profile": "Сохранить профиль",
        "profile_saved": "Профиль сохранён.",
        "home": "Главная",
        "practice": "Практика",
        "dashboard": "Аналитика",
        "bank": "Банк задач",
        "responsible": "Ответственный ИИ",
        "choose_topic": "Выберите тему",
        "choose_problem": "Выберите задачу",
        "difficulty": "Сложность",
        "problem": "Задача",
        "instructions": "Пишите каждый математический шаг с новой строки. Можно использовать `*`, `/`, `^`, `sqrt(...)`, `sin(...)` и `=`.",
        "solution_steps": "Шаги решения",
        "evaluate": "Проверить шаги",
        "need_steps": "Введите хотя бы один шаг решения.",
        "result": "Анализ шагов",
        "step": "Шаг",
        "status": "Статус",
        "diagnosis": "Тип ошибки",
        "feedback": "Комментарий ИИ",
        "correct": "Верно",
        "incorrect": "Нужно исправить",
        "score": "Результат",
        "recommended": "Следующая рекомендация",
        "liked": "Полезно",
        "disliked": "Не полезно",
        "no_attempts": "Попыток пока нет. Решите задачу на странице практики.",
        "attempts": "Попытки",
        "accuracy": "Точность шагов",
        "weaknesses": "Частые ошибки",
        "download": "Скачать результаты в CSV",
        "all_topics": "Все темы",
        "about_scope": "Эта версия настроена только для учащихся Узбекистана: страна фиксирована, доступны 1–11 классы, академический лицей, университет, регионы Узбекистана и задачи в контексте UZS.",
        "not_endorsement": "Это демонстрационный продукт, а не официальный продукт или утверждённая система оценивания государственных органов Узбекистана.",
    },
    "en": {
        "app_title": "Uzbekistan AI Math Mentor",
        "tagline": "An AI assistant that checks every solution step, diagnoses errors, and recommends suitable practice.",
        "country": "Country",
        "country_value": "Uzbekistan",
        "language": "Interface language",
        "profile": "Student profile",
        "name": "Name or nickname",
        "region": "Region",
        "stage": "Education stage",
        "grade": "Grade/course",
        "level": "Current level",
        "save_profile": "Save profile",
        "profile_saved": "Profile saved.",
        "home": "Home",
        "practice": "Practice",
        "dashboard": "Analytics",
        "bank": "Problem bank",
        "responsible": "Responsible AI",
        "choose_topic": "Choose a topic",
        "choose_problem": "Choose a problem",
        "difficulty": "Difficulty",
        "problem": "Problem",
        "instructions": "Write each mathematical step on a new line. You may use `*`, `/`, `^`, `sqrt(...)`, `sin(...)`, and `=`.",
        "solution_steps": "Solution steps",
        "evaluate": "Check steps",
        "need_steps": "Enter at least one solution step.",
        "result": "Step analysis",
        "step": "Step",
        "status": "Status",
        "diagnosis": "Error type",
        "feedback": "AI feedback",
        "correct": "Correct",
        "incorrect": "Needs revision",
        "score": "Score",
        "recommended": "Recommended next",
        "liked": "Helpful",
        "disliked": "Not helpful",
        "no_attempts": "No attempts yet. Solve a problem on the Practice page.",
        "attempts": "Attempts",
        "accuracy": "Step accuracy",
        "weaknesses": "Frequent errors",
        "download": "Download results as CSV",
        "all_topics": "All topics",
        "about_scope": "This version is configured only for learners in Uzbekistan: the country is fixed, with Grades 1–11, academic lyceum and university stages, Uzbekistan regions, and UZS-context problems.",
        "not_endorsement": "This prototype is not an official product or approved assessment system of any Uzbekistan government authority.",
    },
}

REGIONS = [
    "Qoraqalpog‘iston Respublikasi",
    "Andijon viloyati",
    "Buxoro viloyati",
    "Farg‘ona viloyati",
    "Jizzax viloyati",
    "Xorazm viloyati",
    "Namangan viloyati",
    "Navoiy viloyati",
    "Qashqadaryo viloyati",
    "Samarqand viloyati",
    "Sirdaryo viloyati",
    "Surxondaryo viloyati",
    "Toshkent viloyati",
    "Toshkent shahri",
]

STAGES = {
    "uz": ["Maktab (1–11-sinf)", "Akademik litsey", "Universitet"],
    "ru": ["Школа (1–11 класс)", "Академический лицей", "Университет"],
    "en": ["School (Grades 1–11)", "Academic lyceum", "University"],
}

LEVELS = {
    "uz": ["Boshlang‘ich", "O‘rta", "Yuqori"],
    "ru": ["Начальный", "Средний", "Продвинутый"],
    "en": ["Entry", "Intermediate", "Advanced"],
}


def tr(lang: str, key: str) -> str:
    return TEXT.get(lang, TEXT["en"]).get(key, key)
