[theme]
base = "dark"
primaryColor = "#0047FF"
backgroundColor = "#080808"
secondaryBackgroundColor = "#151515"
textColor = "#F7F7F7"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
